//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoHoaApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_NhanVien
    {
        public int NhanVienID { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string CMND { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual S_Users S_Users { get; set; }
    }
}
